export const sizes = [
  'iphone-5',
  ['iphone-5', 'landscape'],
  'samsung-s10',
  ['samsung-s10', 'landscape'],
  'iphone-6',
  ['iphone-6', 'landscape'],
  'iphone-6+',
  ['iphone-6+', 'landscape'],
  'ipad-2',
  ['ipad-2', 'landscape'],
  'macbook-11',
  'macbook-13',
  'macbook-15',
  'macbook-16',
  [1920, 1080],
  [2048, 1152],
]

export const pages = [
  '/',
  '/about-us',
  '/about-us/governance',
  '/about-us/guilds',
  '/about-us/projects',
  '/about-us/community-calls',
  '/about-us/nodes',
  '/work-with-us',
  '/read',
  '/token',
  '/listen',
  '/join-us',
]
