export const sizes = [
  'iphone-5',
  ['iphone-5', 'landscape'],
  'samsung-s10',
  ['samsung-s10', 'landscape'],
  'iphone-6',
  ['iphone-6', 'landscape'],
  'iphone-6+',
  ['iphone-6+', 'landscape'],
  'ipad-2',
  ['ipad-2', 'landscape'],
  'macbook-11',
  'macbook-13',
  'macbook-15',
  'macbook-16',
  [1920, 1080],
  [2048, 1152],
]

export const pages = [
  '/bankless-website',
  '/bankless-websiteabout-us',
  '/bankless-websiteabout-us/governance',
  '/bankless-websiteabout-us/guilds',
  '/bankless-websiteabout-us/projects',
  '/bankless-websiteabout-us/community-calls',
  '/bankless-websiteabout-us/nodes',
  '/bankless-websitework-with-us',
  '/bankless-websiteread',
  '/bankless-websitetoken',
  '/bankless-websitelisten',
  '/bankless-websitejoin-us',
]
